### PR TITLE
Bug fixes for double click event support

### PR DESCRIPTION
**Pull request by nabn**

### CODE REVIEW

**Review by rkhub — APPROVED** [review]

**Review by renaldas-kerpe-arria — APPROVED** [review]

**Comment by renaldas-kerpe-arria** [comment]
Looks good, thanks!

P.S. I have added Raj (@rkhub) to this project too, so everyone on FE team should now have access.

**Comment by renaldas-kerpe-arria** [comment]
P.P.S This still needs to be merged and tagged.

**Comment by renaldas-kerpe-arria** [comment]
Was this tagged after the merge? I think Studio app master is trying to pull the "double-click" branch which no longer exists.

Update: I have tagged this and fixed Studio master build to pull the tag.

**Comment by nabn** [comment]
Thanks for taking care of this. 

This is my fault as I merged studio branch with ref to double-click as priyanka needed something to test and this PR was not approved yet. Didn't realize that it would cause test failures.

**Comment by renaldas-kerpe-arria** [comment]
No worries. It weren't the tests that were failing though, it was npm install that was throwing an error when it could not checkout the ng2-tree from the double-click branch. 

This happened to me too before, but I managed to restore the deleted branch before anyone noticed 😄.

**Pull request merged**
